
#
#      _   _ _           _         ____             _     _       _
#     | \ | (_) ___ ___ | | __ _  | __ ) _ __ _   _| |__ (_)_ __ ( )___
#     |  \| | |/ __/ _ \| |/ _` | |  _ \| '__| | | | '_ \| | '_ \|// __|
#     | |\  | | (_| (_) | | (_| | | |_) | |  | |_| | | | | | | | | \__ \
#     |_| \_|_|\___\___/|_|\__,_| |____/|_|   \__,_|_| |_|_|_| |_| |___/
#                                 _                      __ _
#      _ __   ___ ___ _ __   ___ | |_    ___ ___  _ __  / _(_) __ _
#     | '_ \ / __/ __| '_ \ / _ \| __|  / __/ _ \| '_ \| |_| |/ _` |
#     | | | | (__\__ \ |_) | (_) | |_  | (_| (_) | | | |  _| | (_| |
#     |_| |_|\___|___/ .__/ \___/ \__|  \___\___/|_| |_|_| |_|\__, |
#                    |_|                                      |___/
#
#

# Documentation of the config values can be found here:
# https://github.com/hrkfdn/ncspot/blob/main/doc/users.md#library
#
# At the time of writing, not all configs are documented and you might have to
# look at the source code to discover them.

# Tabs to show in library screen
# Array of "tracks", "albums", "artists", "playlists", "podcasts", "browse"
library_tabs = [ "playlists", "artists", "albums" ]

# Disable all the default keybindings
default_keybindings = false

[keybindings]

# Vim-like motion
"j" = "move down 1"
"k" = "move up 1"
"h" = "move left 1"
"l" = "move right 1"
"g" = "move top"
"G" = "move bottom"

"H" = "previous"   # Play previous song
"L" = "next"       # Play next song
"J" = "shift down" # Move selected song down in queue
"K" = "shift up"   # Move selected song up in queue

# yank and delete like in vim
"d" = "delete"
"y" = "share selected"

"Esc" = "back"
"Space" = "playpause"     # Toggle playback using space bar
"Enter" = "play selected"
"o"     = "open selected"

# Queue settings
"W" = "playnext selected" # Add selected to front of queue
"w" = "queue selected"    # Add selected to back of queue
"c" = "clear"             # Clear queue completely

# Navigation
"q" = "focus queue"
"s" = "focus search"
"f" = "focus library"

# Theme that mimicks the colors of Spotify's official client.
#
# Taken from https://github.com/hrkfdn/ncspot/pull/40
# There are many more cool themes in that pull request.
[theme]
background = "black"
primary = "light white"
secondary = "light black"
title = "green"
playing = "green"
playing_bg = "black"
highlight = "light white"
highlight_bg = "#484848"
error = "light white"
error_bg = "red"
statusbar = "black"
statusbar_progress = "green"
statusbar_bg = "green"
cmdline = "light white"
cmdline_bg = "black"

# Login using pass
[credentials]
username_cmd = "pass show pub/spotify.com/username"
password_cmd = "pass show pub/spotify.com/password"
