#!/bin/sh
#
# Connect to the ETH VPN with openconnect.
#
# Authenticates automatically using pass
#
# Official information from ETH concerning VPN usage:
# https://www.isg.inf.ethz.ch/Main/ServicesNetworkVPN

# We want the script to fail if any command fails.
# E.g. if we fail to get the password.
set -e

hostname=$(cat /proc/sys/kernel/hostname)
sys_username=$(whoami)
sys_password=$(pass show priv/${hostname}/${sys_username}/password)

eth_username=$(pass show eth/radius/username)
eth_password=$(pass show eth/radius/password)
totp_token=$(pass otp show eth/active_directory/totp)

# Get password from stdin to avoid leaking the password in the process list or
# in logs.
sudo --reset-timestamp --stdin openconnect \
    --user ${eth_username}@student-net.ethz.ch \
    --useragent=AnyConnect \
    --usergroup student-net \
    --passwd-on-stdin \
    https://sslvpn.ethz.ch \
    << EOF
${sys_password}
${eth_password}
${totp_token}
EOF
